version: '2'
services:
  icecast:
    build: ./icecast
    ports:
      - "8000:8000"
    expose:
      - "8000"
  darkice:
    privileged: true
    build: ./darkice
    depends_on:
      - icecast
  ddns:
    build: ./ddns
    network_mode: "host"