FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:1.14.6-build as build

COPY . ./
RUN go build

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:1.14.6-run
COPY --from=build ddns ./

CMD ["./ddns"]