FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:1.14.6-build as build

COPY . ./

ENV GO111MODULE=on

RUN CGO_ENABLED=0 GOOS=linux go build

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:1.14.6-run
COPY --from=build ddns ./

CMD ["./ddns"]